server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_interview?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml